BEGIN;

-- NPC quest items / rewards (full columns + upsert)
INSERT INTO items (
  code,
  name,
  category,
  slot,
  rarity,
  descr,
  description,
  stack_max,
  weight,
  tradable,
  bind_on_pickup,
  npc_key,
  is_archived,
  is_global,
  amount,
  stackable,
  sell_price,
  atk,
  defense,
  hp,
  mp,
  level_req,
  class_req,
  appearance_text,
  emoji,
  stats,
  is_active,
  is_lootable,
  is_craftable,
  base_value,
  created_at,
  updated_at
)
VALUES
-- ─────────────────────────────
-- OKSANA
-- ─────────────────────────────
(
  'q_wax_charm',
  'Віск-оберіг',
  'misc',
  'other',
  'Звичайний',
  'Чистий віск, благий до свічок.',
  'Чистий віск, благий до свічок.',
  99, 1, false, true,
  'berehynia_oksana',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"berehynia_oksana","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_oksana_holy_candle',
  'Свята свічка Оксани',
  'misc',
  'other',
  'Рідкісний',
  'Тепле полум’я дає відчуття захисту.',
  'Тепле полум’я дає відчуття захисту.',
  1, 1, false, true,
  'berehynia_oksana',
  false, false,
  1, false,
  10, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"berehynia_oksana","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),
(
  'q_red_thread',
  'Червона нитка',
  'misc',
  'other',
  'Звичайний',
  'Нитка для оберегів і вузлів пам’яті.',
  'Нитка для оберегів і вузлів пам’яті.',
  99, 1, false, true,
  'berehynia_oksana',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"berehynia_oksana","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_st_johns_wort',
  'Сухоцвіт звіробою',
  'misc',
  'other',
  'Звичайний',
  'Теплий трав’яний оберіг від холоду й страху.',
  'Теплий трав’яний оберіг від холоду й страху.',
  99, 1, false, true,
  'berehynia_oksana',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"berehynia_oksana","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_oksana_knot_charm',
  'Оберіг-вузлик',
  'misc',
  'other',
  'Рідкісний',
  'Малий вузлик, що тримає думку в купі.',
  'Малий вузлик, що тримає думку в купі.',
  1, 1, false, true,
  'berehynia_oksana',
  false, false,
  1, false,
  12, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"berehynia_oksana","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),

-- ─────────────────────────────
-- SEMEN
-- ─────────────────────────────
(
  'q_werewolf_claws',
  'Кігті яружного вовкулаки',
  'misc',
  'other',
  'Звичайний',
  'Гострі й темні від давньої скверни.',
  'Гострі й темні від давньої скверни.',
  99, 1, false, true,
  'lirnyk_semen',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"lirnyk_semen","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_semen_silver_coin',
  'Срібний медяк Семена',
  'misc',
  'other',
  'Рідкісний',
  'Дзвенить, мов струна. На щастя.',
  'Дзвенить, мов струна. На щастя.',
  1, 1, false, true,
  'lirnyk_semen',
  false, false,
  1, false,
  15, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"lirnyk_semen","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),
(
  'q_creaky_wedge',
  'Скрипучий ладок',
  'misc',
  'other',
  'Звичайний',
  'Старий дерев’яний клин для лагодження ліри.',
  'Старий дерев’яний клин для лагодження ліри.',
  99, 1, false, true,
  'lirnyk_semen',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"lirnyk_semen","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_leather_gut',
  'Жила зі шкіри',
  'misc',
  'other',
  'Звичайний',
  'Міцна жила для струн.',
  'Міцна жила для струн.',
  99, 1, false, true,
  'lirnyk_semen',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"lirnyk_semen","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_semen_buckle',
  'Лірницька пряжка',
  'misc',
  'other',
  'Рідкісний',
  'Пряжка, що дзвенить у такт. На щастя.',
  'Пряжка, що дзвенить у такт. На щастя.',
  1, 1, false, true,
  'lirnyk_semen',
  false, false,
  1, false,
  14, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"lirnyk_semen","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),

-- ─────────────────────────────
-- PANAS
-- ─────────────────────────────
(
  'q_duckweed',
  'Ряска болотяна',
  'misc',
  'other',
  'Звичайний',
  'Зелень із тихих плес.',
  'Зелень із тихих плес.',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_oak_moss',
  'Мох дубовий',
  'misc',
  'other',
  'Звичайний',
  'Сухий, але міцний.',
  'Сухий, але міцний.',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_glass_vial',
  'Скляна банька',
  'misc',
  'other',
  'Звичайний',
  'Щоб не бахкало — потрібен посуд.',
  'Щоб не бахкало — потрібен посуд.',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'c_stabilization_potion',
  'Зілля стабілізації',
  'consumable',
  'other',
  'Звичайний',
  'Трохи гальмує вибухові сюрпризи.',
  'Трохи гальмує вибухові сюрпризи.',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  8, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"reward","consumable":true}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),
(
  'q_hearth_chalk',
  'Крейда з печі',
  'misc',
  'other',
  'Звичайний',
  'Біла крейда, щоб креслити кола й не влізти в біду.',
  'Біла крейда, щоб креслити кола й не влізти в біду.',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_boiler_soot',
  'Сажа котлова',
  'misc',
  'other',
  'Звичайний',
  'Сажа для “заземлення” вибриків зілля.',
  'Сажа для “заземлення” вибриків зілля.',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'c_muffle_powder',
  'Порошок приглушення',
  'consumable',
  'other',
  'Звичайний',
  'Зменшує шанс небажаних ефектів (тимчасово).',
  'Зменшує шанс небажаних ефектів (тимчасово).',
  99, 1, false, true,
  'nedochaklun_panas',
  false, false,
  1, true,
  6, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nedochaklun_panas","kind":"reward","consumable":true}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),

-- ─────────────────────────────
-- NASTIA
-- ─────────────────────────────
(
  'q_spice_box',
  'Скринька спецій',
  'misc',
  'other',
  'Звичайний',
  'Суміш гостра, як язик Насті.',
  'Суміш гостра, як язик Насті.',
  99, 1, false, true,
  'nastia_salt_belly',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nastia_salt_belly","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_carrier_seal',
  'Печатка перевізника',
  'misc',
  'other',
  'Звичайний',
  'Знак, що вантаж пройшов огляд.',
  'Знак, що вантаж пройшов огляд.',
  99, 1, false, true,
  'nastia_salt_belly',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nastia_salt_belly","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_saltbelly_voucher',
  'Талон «Солоний Киш»',
  'misc',
  'other',
  'Рідкісний',
  'Знижка від Насті.',
  'Знижка від Насті.',
  1, 1, false, true,
  'nastia_salt_belly',
  false, false,
  1, false,
  12, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nastia_salt_belly","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),
(
  'q_debtors_list',
  'Список боржників',
  'misc',
  'other',
  'Звичайний',
  'Папірці, що пахнуть проблемами й прибутком.',
  'Папірці, що пахнуть проблемами й прибутком.',
  99, 1, false, true,
  'nastia_salt_belly',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nastia_salt_belly","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_customs_plomb',
  'Пломба митника',
  'misc',
  'other',
  'Звичайний',
  'Офіційний знак. Не питай, як дістався.',
  'Офіційний знак. Не питай, як дістався.',
  99, 1, false, true,
  'nastia_salt_belly',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nastia_salt_belly","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_discount_coupon',
  'Купон на знижку',
  'misc',
  'other',
  'Рідкісний',
  'Можна виторгувати дрібну вигоду.',
  'Можна виторгувати дрібну вигоду.',
  1, 1, false, true,
  'nastia_salt_belly',
  false, false,
  1, false,
  10, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"nastia_salt_belly","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),

-- ─────────────────────────────
-- YURKO
-- ─────────────────────────────
(
  'q_gnus_fang',
  'Ікло степового гнуса',
  'misc',
  'other',
  'Звичайний',
  'Маленьке, та капосне.',
  'Маленьке, та капосне.',
  99, 1, false, true,
  'yurko_rekrut',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"yurko_rekrut","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_courage_patch',
  'Нашивка відваги',
  'misc',
  'other',
  'Рідкісний',
  'Носиш — і не пасуєш.',
  'Носиш — і не пасуєш.',
  1, 1, false, true,
  'yurko_rekrut',
  false, false,
  1, false,
  14, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"yurko_rekrut","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
),
(
  'q_scabbard_strap',
  'Ремінець для піхов',
  'misc',
  'other',
  'Звичайний',
  'Щоб меч не бовтався, як язик у шинку.',
  'Щоб меч не бовтався, як язик у шинку.',
  99, 1, false, true,
  'yurko_rekrut',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"yurko_rekrut","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  'q_button_knope',
  'Кнопа-ґудзик',
  'misc',
  'other',
  'Звичайний',
  'Дрібниця, але без неї все тримається на чесному слові.',
  'Дрібниця, але без неї все тримається на чесному слові.',
  99, 1, false, true,
  'yurko_rekrut',
  false, false,
  1, true,
  0, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"yurko_rekrut","kind":"require"}'::jsonb,
  true, true, false,
  1, NOW(), NOW()
),
(
  't_recruit_memo',
  'Пам’ятка рекрута',
  'misc',
  'other',
  'Рідкісний',
  'Папірець із правилами виживання. Смішно, але працює.',
  'Папірець із правилами виживання. Смішно, але працює.',
  1, 1, false, true,
  'yurko_rekrut',
  false, false,
  1, false,
  12, 0,0,0,0,
  1, NULL, NULL, NULL,
  '{"quest_item":true,"npc":"yurko_rekrut","kind":"reward"}'::jsonb,
  true, false, false,
  1, NOW(), NOW()
)

ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  slot = EXCLUDED.slot,
  rarity = EXCLUDED.rarity,
  descr = EXCLUDED.descr,
  description = EXCLUDED.description,
  stack_max = EXCLUDED.stack_max,
  weight = EXCLUDED.weight,
  tradable = EXCLUDED.tradable,
  bind_on_pickup = EXCLUDED.bind_on_pickup,
  npc_key = EXCLUDED.npc_key,
  is_archived = EXCLUDED.is_archived,
  is_global = EXCLUDED.is_global,
  amount = EXCLUDED.amount,
  stackable = EXCLUDED.stackable,
  sell_price = EXCLUDED.sell_price,
  atk = EXCLUDED.atk,
  defense = EXCLUDED.defense,
  hp = EXCLUDED.hp,
  mp = EXCLUDED.mp,
  level_req = EXCLUDED.level_req,
  class_req = EXCLUDED.class_req,
  appearance_text = EXCLUDED.appearance_text,
  emoji = EXCLUDED.emoji,
  stats = EXCLUDED.stats,
  is_active = EXCLUDED.is_active,
  is_lootable = EXCLUDED.is_lootable,
  is_craftable = EXCLUDED.is_craftable,
  base_value = EXCLUDED.base_value,
  updated_at = NOW();

COMMIT;