// Runtime env injected by /config.js (generated by docker-entrypoint)
// NOTE: Railway часто має змінні з префіксом NEXT_PUBLIC_ (з Next.js), тому ми робимо fallback.

export type RuntimeEnv = {
  // preferred (Vite)
  VITE_API_BASE_URL?: string
  VITE_TG_BOT_USERNAME?: string
  VITE_API_DEBUG?: string

  // fallbacks (Railway / Next.js style)
  NEXT_PUBLIC_API_BASE?: string
  NEXT_PUBLIC_API_BASE_URL?: string
  NEXT_PUBLIC_TG_BOT_USERNAME?: string
  NEXT_PUBLIC_API_DEBUG?: string
}

declare global {
  interface Window {
    __ENV__?: RuntimeEnv
  }
}

const runtime = (typeof window !== 'undefined' ? window.__ENV__ : undefined) as RuntimeEnv | undefined

const clean = (v?: unknown): string | undefined => {
  if (typeof v !== 'string') return undefined
  const s = v.trim()
  if (!s || s === 'undefined' || s === 'null') return undefined
  return s
}

const readAny = (...keys: (keyof RuntimeEnv)[]): string | undefined => {
  for (const key of keys) {
    // 1) runtime /config.js
    const r = clean(runtime?.[key])
    if (r) return r

    // 2) Vite build-time env
    const v = clean((import.meta as any)?.env?.[key])
    if (v) return v

    // 3) SSR / Node env (fallback)
    const p = clean(typeof process !== 'undefined' ? (process as any).env?.[key as string] : undefined)
    if (p) return p
  }
  return undefined
}

export const API_BASE_URL = (readAny('VITE_API_BASE_URL', 'NEXT_PUBLIC_API_BASE', 'NEXT_PUBLIC_API_BASE_URL') ?? '').replace(
  /\/$/,
  '',
)

export const TG_BOT_USERNAME = readAny('VITE_TG_BOT_USERNAME', 'NEXT_PUBLIC_TG_BOT_USERNAME') ?? ''

export const API_DEBUG = (readAny('VITE_API_DEBUG', 'NEXT_PUBLIC_API_DEBUG') ?? '').toLowerCase() === 'true'