import type { Config } from 'tailwindcss'

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        card: 'rgb(var(--card) / <alpha-value>)',
        cardForeground: 'rgb(var(--card-foreground) / <alpha-value>)',
        popover: 'rgb(var(--popover) / <alpha-value>)',
        popoverForeground: 'rgb(var(--popover-foreground) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        primaryForeground: 'rgb(var(--primary-foreground) / <alpha-value>)',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        secondaryForeground: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        mutedForeground: 'rgb(var(--muted-foreground) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        accentForeground: 'rgb(var(--accent-foreground) / <alpha-value>)',
        destructive: 'rgb(var(--destructive) / <alpha-value>)',
        destructiveForeground: 'rgb(var(--destructive-foreground) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        input: 'rgb(var(--input) / <alpha-value>)',
        ring: 'rgb(var(--ring) / <alpha-value>)',

        spd: {
          bg: 'rgb(var(--spd-bg) / <alpha-value>)',
          panel: 'rgb(var(--spd-panel) / <alpha-value>)',
          panel2: 'rgb(var(--spd-panel-2) / <alpha-value>)',
          frame: 'rgb(var(--spd-frame) / <alpha-value>)',
          frameHi: 'rgb(var(--spd-frame-hi) / <alpha-value>)',
          frameLo: 'rgb(var(--spd-frame-lo) / <alpha-value>)',
          text: 'rgb(var(--spd-text) / <alpha-value>)',
          textDim: 'rgb(var(--spd-text-dim) / <alpha-value>)',
          gold: 'rgb(var(--spd-gold) / <alpha-value>)',
          hp: 'rgb(var(--spd-hp-red) / <alpha-value>)',
          mana: 'rgb(var(--spd-mana-blue) / <alpha-value>)',
          poison: 'rgb(var(--spd-poison-green) / <alpha-value>)',
          thread: 'rgb(var(--spd-thread-red) / <alpha-value>)',
          turq: 'rgb(var(--spd-turq) / <alpha-value>)',
        },
      },
      transitionDuration: { spd: '160ms' },
      boxShadow: { spd: '0 10px 30px rgba(0,0,0,.35)' },
    },
  },
  plugins: [],
} satisfies Config