// ...
<Input placeholder={t('auth.email_placeholder')} {...form.register('email')} />
// ...
<Input type="password" placeholder={t('auth.password_placeholder')} {...form.register('password')} />
// ...
toast.success(tab === 'login' ? t('auth.login_success') : t('auth.register_success'))
// ...